CREATE DATABASE hack;

USE hack;

CREATE TABLE Catalog (
   SKU_ID INT(15),
   PRODUCT_ID VARCHAR(50),
   DISPLAY_NAME VARCHAR(75),
   BRAND_NAME VARCHAR(50),
   LIST_PRICE VARCHAR(10),
   CATEGORY_NAME VARCHAR (20),
   IS_DEFAULT_SKU INT(1),
   ONLINE_ONLY INT(1),
   DESCRIPTION TEXT,
   LONG_DESCRIPTION MEDIUMTEXT,
   PRIMARY KEY(SKU_ID)
);


LOAD DATA INFILE 'Catalog.csv'
	INTO TABLE Catalog
	FIELDS TERMINATED BY '|' 
	LINES TERMINATED BY '\n'
	IGNORE 1 LINES;






